In [1]:
# Imports
import numpy as np

In [2]:
# Input Parameters
i_size = 3
k_size = 3

In [3]:
# Helper Functions

def create_random_array(w, h):
    array = np.random.randint(0, 9, size=(h, w))
    return array

In [7]:
# Sliding Window Convolution
def convolve_2d(input_matrix, kernel):
    input_rows = len(input_matrix)
    input_cols = len(input_matrix[0])
    kernel_size = len(kernel)
    
    output_rows = input_rows - kernel_size + 1
    output_cols = input_cols - kernel_size + 1
    
    output = [[0 for _ in range(output_cols)] for _ in range(output_rows)]
    
    for i in range(output_rows):
        for j in range(output_cols):
            sum_value = 0
            for ki in range(kernel_size):
                for kj in range(kernel_size):
                    sum_value += input_matrix[i + ki][j + kj] * kernel[ki][kj]
            output[i][j] = sum_value
    
    return output

In [14]:
# Convolution using Toeplitz
def kernel_to_toeplitz(kernel, input_shape):
    m, n = input_shape
    k, _ = kernel.shape
    
    output_rows = m - k + 1
    output_cols = n - k + 1
    
    toeplitz_cols = m * n
    toeplitz_rows = output_rows * output_cols
    
    toeplitz_matrix = np.zeros((toeplitz_rows, toeplitz_cols))
    
    row = 0
    for i in range(output_rows):
        for j in range(output_cols):
            flattened_kernel = np.zeros((m, n))
            flattened_kernel[i:i+k, j:j+k] = kernel
            toeplitz_matrix[row, :] = flattened_kernel.flatten()
            row += 1
    
    return toeplitz_matrix

def convolve_using_toeplitz(input_matrix, kernel):
    input_shape = input_matrix.shape
    toeplitz_matrix = kernel2toeplitz(kernel, input_shape)
    flattened_input = input_matrix.flatten()
    conv_result = toeplitz_matrix @ flattened_input # Matrix multiplication
    output_shape = (input_shape[0] - kernel.shape[0] + 1, input_shape[1] - kernel.shape[1] + 1)
    conv_result = conv_result.reshape(output_shape)
    
    return conv_result

In [15]:
# Example Sliding Window
input_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
kernel = np.array([[1, 2], [3, 4]])

print("Input Matrix")
print(input_matrix)

print("Kernel")
print(kernel)

sliding_convolution = convolve_2d(input_matrix, kernel)
print("Sliding Window Convolution")
print(sliding_convolution)

Input Matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Kernel
[[1 2]
 [3 4]]
Sliding Window Convolution
[[37, 47], [67, 77]]


In [16]:
# Example Toeplitz Matrix
toeplitz_k = kernel_to_toeplitz(kernel, (3,3))
print("Toeplitz Matrix")
print(toeplitz_k)
conv_result = convolve_using_toeplitz(input_matrix, kernel)

print("Toeplitz Matrix Multiplication Convolution")
print(conv_result)

Toeplitz Matrix
[[1. 2. 0. 3. 4. 0. 0. 0. 0.]
 [0. 1. 2. 0. 3. 4. 0. 0. 0.]
 [0. 0. 0. 1. 2. 0. 3. 4. 0.]
 [0. 0. 0. 0. 1. 2. 0. 3. 4.]]
Toeplitz Matrix Multiplication Convolution
[[37. 47.]
 [67. 77.]]


In [ ]:
# Sa